/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetotechdesk.view;

import com.mycompany.projetotechdesk.Model.Contato;
import com.mycompany.projetotechdesk.Model.Empresa;
import com.mycompany.projetotechdesk.Model.Endereco;
import com.mycompany.projetotechdesk.Model.Usuario;
import com.mycompany.projetotechdesk.dao.UsuarioDAO;
import com.mycompany.projetotechdesk.util.placeholder;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());
    
    private UsuarioDAO usuarioDAO;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
        
        this.usuarioDAO = new UsuarioDAO();
        setLocationRelativeTo(null); // Centraliza
        placeholder.adicionarPlaceholder(pswSenhaCadastro, "Senha");
        placeholder.adicionarPlaceholder(pswConfirmarSenhaCadastro, "Confirmar Senha");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new Componentes.RoundedButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeCompletoCadastro = new Componentes.TextField();
        txtEmailCadastro = new Componentes.TextField();
        pswSenhaCadastro = new javax.swing.JPasswordField();
        txtNomeEmpresa = new Componentes.TextField();
        txtTelefone = new Componentes.TextField();
        txtCNPJ = new Componentes.TextField();
        txtCidade = new Componentes.TextField();
        cbxEstado = new javax.swing.JComboBox<>();
        txtBairro = new Componentes.TextField();
        txtLogradouro = new Componentes.TextField();
        txtNumero = new Componentes.TextField();
        btnCadastrar = new Componentes.RoundedButton();
        pswConfirmarSenhaCadastro = new javax.swing.JPasswordField();
        btnFecharCadastro = new Componentes.IconButton();
        btnMinimizarCadastro = new Componentes.IconButton();
        cbMostrarSenhaCadastro = new javax.swing.JCheckBox();
        txtCep = new Componentes.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setForeground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("clique no botão abaixo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Para se conectar conosco novamente,");

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnLogin.setForeground(new java.awt.Color(51, 102, 255));
        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bem-Vindo de Volta!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(69, 69, 69))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(105, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Cadastre Sua Assistência Técnica");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Preencha os campos para criar uma nova conta");

        txtNomeCompletoCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNomeCompletoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCompletoCadastro.setMinimumSize(new java.awt.Dimension(84, 32));
        txtNomeCompletoCadastro.setPlaceholder("Nome Completo:");
        txtNomeCompletoCadastro.setPreferredSize(new java.awt.Dimension(260, 35));

        txtEmailCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmailCadastro.setPlaceholder("Email");
        txtEmailCadastro.setPreferredSize(new java.awt.Dimension(260, 32));

        txtNomeEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNomeEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeEmpresa.setMinimumSize(new java.awt.Dimension(84, 32));
        txtNomeEmpresa.setPlaceholder("Nome Empresa");
        txtNomeEmpresa.setPreferredSize(new java.awt.Dimension(260, 35));

        txtTelefone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setMinimumSize(new java.awt.Dimension(84, 32));
        txtTelefone.setPlaceholder("Telefone");
        txtTelefone.setPreferredSize(new java.awt.Dimension(260, 35));

        txtCNPJ.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        txtCNPJ.setMinimumSize(new java.awt.Dimension(84, 32));
        txtCNPJ.setPlaceholder("CNPJ");
        txtCNPJ.setPreferredSize(new java.awt.Dimension(260, 35));

        txtCidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCidade.setMinimumSize(new java.awt.Dimension(84, 35));
        txtCidade.setPlaceholder("Cidade");
        txtCidade.setPreferredSize(new java.awt.Dimension(260, 32));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "Acre - AC", "Alagoas - AL", "Amapá - AP", "Amazonas - AM", "Bahia - BA", "Ceará - CE", "Distrito Federal - DF", "Espírito Santo - ES", "Goiás - GO", "Maranhão - MA", "Mato Grosso - MT", "Mato Grosso do Sul - MS", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB", "Paraná - PR", "Pernambuco - PE", "Piauí - PI", "Rio de Janeiro - RJ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS", "Rondônia - RO", "Roraima - RR", "Santa Catarina - SC", "São Paulo - SP", "Sergipe - SE", "Tocantins - TO" }));

        txtBairro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBairro.setMinimumSize(new java.awt.Dimension(84, 35));
        txtBairro.setPlaceholder("Bairro");
        txtBairro.setPreferredSize(new java.awt.Dimension(260, 32));

        txtLogradouro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLogradouro.setMinimumSize(new java.awt.Dimension(84, 35));
        txtLogradouro.setPlaceholder("Logradouro");
        txtLogradouro.setPreferredSize(new java.awt.Dimension(260, 32));

        txtNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumero.setMinimumSize(new java.awt.Dimension(84, 35));
        txtNumero.setPlaceholder("Número");
        txtNumero.setPreferredSize(new java.awt.Dimension(260, 32));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnFecharCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        btnFecharCadastro.setText("");
        btnFecharCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCadastroActionPerformed(evt);
            }
        });

        btnMinimizarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar azul.png"))); // NOI18N
        btnMinimizarCadastro.setText("");
        btnMinimizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarCadastroActionPerformed(evt);
            }
        });

        cbMostrarSenhaCadastro.setText("mostrar senha");
        cbMostrarSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarSenhaCadastroActionPerformed(evt);
            }
        });

        txtCep.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCep.setMinimumSize(new java.awt.Dimension(84, 35));
        txtCep.setPlaceholder("CEP");
        txtCep.setPreferredSize(new java.awt.Dimension(260, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMostrarSenhaCadastro)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtLogradouro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmailCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNomeCompletoCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pswSenhaCadastro)
                                        .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(pswConfirmarSenhaCadastro)
                                        .addComponent(jLabel1)))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMinimizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFecharCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFecharCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btnMinimizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCompletoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswConfirmarSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(cbMostrarSenhaCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCadastroActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFecharCadastroActionPerformed

    private void btnMinimizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarCadastroActionPerformed
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarCadastroActionPerformed

    private void cbMostrarSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarSenhaCadastroActionPerformed
        if (cbMostrarSenhaCadastro.isSelected()) {
            pswSenhaCadastro.setEchoChar((char) 0);
            pswConfirmarSenhaCadastro.setEchoChar((char) 0);
        }else {
            pswSenhaCadastro.setEchoChar('*');
            pswConfirmarSenhaCadastro.setEchoChar('*');
        }
    }//GEN-LAST:event_cbMostrarSenhaCadastroActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        //validaçao da senha
        String senha = new String(pswSenhaCadastro.getPassword());
        String confirmarSenha = new String(pswConfirmarSenhaCadastro.getPassword());
        
        if (!senha.equals(confirmarSenha)) {
            JOptionPane.showMessageDialog(this, "As senhas não conferem!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validaçao de campos obrigatorios
        if (txtNomeEmpresa.getText().trim().isEmpty() ||
                txtEmailCadastro.getText().trim().isEmpty() ||
                senha.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatorios (Empresa, Email, Senha).", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            //montar Objetos empresa
            Empresa empresa = new Empresa();
            empresa.setNomeEmpresa(txtNomeEmpresa.getText());
            empresa.setCnpj(txtCNPJ.getText());
            
            //montar objeto contato
            Contato contato = new Contato();
            contato.setEmail(txtEmailCadastro.getText());
            contato.setTelefone(txtTelefone.getText());
            
            //montar objetos Endereço
            Endereco endereco = new Endereco();
            endereco.setCidade(txtCidade.getText());
            
            if (cbxEstado.getSelectedIndex() > 0) {
                endereco.setEstado(cbxEstado.getSelectedItem().toString());
            } else {
                endereco.setEstado("");
            }
            
            endereco.setLogradouro(txtLogradouro.getText());
            endereco.setBairro(txtBairro.getText());
            endereco.setNumero(txtNumero.getText());
            endereco.setCep(txtCep.getText());
            
            //montar objeto Usuario (admin)
            Usuario admin = new Usuario();
            admin.setNomeUsuario(txtNomeCompletoCadastro.getText());
            admin.setSenha(senha);
            
            //vincula os objetos auxiliares ao usuario principal
            admin.setContato(contato);
            admin.setEndereco(endereco);
            
            //chama o DAO para salvar
            boolean sucesso = usuarioDAO.registrarNovaEmpresaEUsuario(empresa, admin);
            
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!\nFaça login para começar.");
                
            } else {
                JOptionPane.showMessageDialog(this, "ERRO ao cadastrar.\nVerifique se o email ou CNPJ ja existem.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO inesperado: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.RoundedButton btnCadastrar;
    private Componentes.IconButton btnFecharCadastro;
    private Componentes.RoundedButton btnLogin;
    private Componentes.IconButton btnMinimizarCadastro;
    private javax.swing.JCheckBox cbMostrarSenhaCadastro;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pswConfirmarSenhaCadastro;
    private javax.swing.JPasswordField pswSenhaCadastro;
    private Componentes.TextField txtBairro;
    private Componentes.TextField txtCNPJ;
    private Componentes.TextField txtCep;
    private Componentes.TextField txtCidade;
    private Componentes.TextField txtEmailCadastro;
    private Componentes.TextField txtLogradouro;
    private Componentes.TextField txtNomeCompletoCadastro;
    private Componentes.TextField txtNomeEmpresa;
    private Componentes.TextField txtNumero;
    private Componentes.TextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
