/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetotechdesk.view;

import com.mycompany.projetotechdesk.Model.Cliente;
import com.mycompany.projetotechdesk.Model.Endereco;
import com.mycompany.projetotechdesk.dao.EnderecoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class TelaEndereco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEndereco.class.getName());
    
    private int idUsuario;
    private String nomeDono;
    private String enderecoSelecionado = null;
    private EnderecoDAO dao = new EnderecoDAO();
    private boolean modoEdicao = false;
    /**
     * Creates new form Endereco
     */
    public TelaEndereco() {
        initComponents();
    }
    
    public TelaEndereco(int id, String tipo, String nome) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
        this.idUsuario = id;
        this.nomeDono = nome;
        
        
        // Muda o título da janela ou um label para mostrar de quem é
        // lblTitulo.setText("Endereços de: " + nome);
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Fecha só essa janela
        
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnEditar = new Componentes.RoundedButton();
        txtDescricao = new Componentes.TextField();
        txtLogradouro = new Componentes.TextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnderecos = new javax.swing.JTable();
        txtCidade = new Componentes.TextField();
        btnSalvar = new Componentes.RoundedButton();
        txtBairro = new Componentes.TextField();
        txtCep = new Componentes.TextField();
        txtNumero = new Componentes.TextField();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new Componentes.RoundedButton();
        btnMinimizarEndereco = new Componentes.IconButton();
        btnFecharEndereco = new Componentes.IconButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "Acre - AC", "Alagoas - AL", "Amapá - AP", "Amazonas - AM", "Bahia - BA", "Ceará - CE", "Distrito Federal - DF", "Espírito Santo - ES", "Goiás - GO", "Maranhão - MA", "Mato Grosso - MT", "Mato Grosso do Sul - MS", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB", "Paraná - PR", "Pernambuco - PE", "Piauí - PI", "Rio de Janeiro - RJ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS", "Rondônia - RO", "Roraima - RR", "Santa Catarina - SC", "São Paulo - SP", "Sergipe - SE", "Tocantins - TO" }));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtDescricao.setPlaceholder("Descrição");

        txtLogradouro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLogradouro.setMinimumSize(new java.awt.Dimension(84, 35));
        txtLogradouro.setPlaceholder("Logradouro");
        txtLogradouro.setPreferredSize(new java.awt.Dimension(260, 32));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(8, 118, 132));
        jLabel32.setText("Endereço");

        tblEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Logradouro", "Numero", "Bairro", "Cidade", "Estado", "Cep"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnderecos);

        txtCidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCidade.setMinimumSize(new java.awt.Dimension(84, 35));
        txtCidade.setPlaceholder("Cidade");
        txtCidade.setPreferredSize(new java.awt.Dimension(260, 32));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtBairro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBairro.setMinimumSize(new java.awt.Dimension(84, 35));
        txtBairro.setPlaceholder("Bairro");
        txtBairro.setPreferredSize(new java.awt.Dimension(260, 32));

        txtCep.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCep.setMinimumSize(new java.awt.Dimension(84, 35));
        txtCep.setPlaceholder("CEP");
        txtCep.setPreferredSize(new java.awt.Dimension(260, 32));

        txtNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumero.setMinimumSize(new java.awt.Dimension(84, 35));
        txtNumero.setPlaceholder("Número");
        txtNumero.setPreferredSize(new java.awt.Dimension(260, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Informe seus dados");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnMinimizarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar azul.png"))); // NOI18N
        btnMinimizarEndereco.setText("");
        btnMinimizarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarEnderecoActionPerformed(evt);
            }
        });

        btnFecharEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        btnFecharEndereco.setText("");
        btnFecharEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(107, 107, 107)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinimizarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(619, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimizarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecharEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
                                          
        
        try {
            // Validação simples (opcional)
            if (txtLogradouro.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O logradouro é obrigatório.");
                return;
            }

            Endereco e = new Endereco();
            
            // Dados comuns para Salvar ou Atualizar
            e.setDescricao(txtDescricao.getText()); // Essa linha precisa valer para os dois casos!
            e.setLogradouro(txtLogradouro.getText());
            e.setNumero(txtNumero.getText());
            e.setBairro(txtBairro.getText());
            e.setCidade(txtCidade.getText());
            if (cbxEstado.getSelectedItem() != null) {
                e.setEstado(cbxEstado.getSelectedItem().toString());
            } else {
                e.setEstado("");
            }
            e.setCep(txtCep.getText());

            if (modoEdicao == false) {
                // ---- NOVO ----
                dao.adicionar(e, idUsuario);
                JOptionPane.showMessageDialog(null, "Endereço salvo com sucesso!");
            } else {
                // ---- ATUALIZAR ----
                e.setId(Integer.parseInt(enderecoSelecionado));
                dao.atualizar(e);
                JOptionPane.showMessageDialog(null, "Endereço atualizado com sucesso!");
            }
            
            limpar();          // Limpa a tela APÓS salvar
            atualizarTabela(); // Recarrega a tabela com os dados novos
            modoEdicao = false;
            btnSalvar.setText("Salvar");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + ex.getMessage());
            ex.printStackTrace();
        }
    
    
        

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblEnderecos.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um endereço para editar!");
            return;
        }

        // Função para evitar erro de nulo
        java.util.function.Function<Object, String> safeStr = obj -> (obj == null) ? "" : obj.toString();

        try {
            enderecoSelecionado = safeStr.apply(tblEnderecos.getValueAt(linha, 0));

            // Preenche campos de texto simples
            txtDescricao.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 1)));
            txtLogradouro.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 2)));
            txtNumero.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 3)));
            txtBairro.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 4)));
            txtCidade.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 5)));

            // --- CORREÇÃO DA SELEÇÃO DO ESTADO ---
            // Coluna 6 é o Estado
            String estadoTabela = safeStr.apply(tblEnderecos.getValueAt(linha, 6)).trim();
            
            // 1. Tenta selecionar direto (caso o texto seja idêntico)
            cbxEstado.setSelectedItem(estadoTabela);

            // 2. Se não selecionou (porque os textos são ligeiramente diferentes), procura na raça
            String selecionadoAgora = (cbxEstado.getSelectedItem() != null) ? cbxEstado.getSelectedItem().toString() : "";
            
            if (!estadoTabela.isEmpty() && !selecionadoAgora.equals(estadoTabela)) {
                // Percorre todos os itens da ComboBox para achar um parecido
                for (int i = 0; i < cbxEstado.getItemCount(); i++) {
                    String itemLista = cbxEstado.getItemAt(i);
                    
                    if (itemLista != null) {
                        String itemLimpo = itemLista.trim().toUpperCase(); // Ex: "PARANÁ - PR"
                        String tabelaLimpo = estadoTabela.toUpperCase();   // Ex: "PR" ou "PARANA"
                        
                        // Verifica se um contém o outro (Resolve "PR" vs "Paraná - PR")
                        if (itemLimpo.equals(tabelaLimpo) || 
                            itemLimpo.contains(tabelaLimpo) || 
                            tabelaLimpo.contains(itemLimpo)) {
                            
                            cbxEstado.setSelectedIndex(i);
                            break; // Achou! Para o loop.
                        }
                    }
                }
            }
            
            // Coluna 7 é o CEP
            txtCep.setText(safeStr.apply(tblEnderecos.getValueAt(linha, 7)));

            modoEdicao = true;
            btnSalvar.setText("Atualizar");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int row = tblEnderecos.getSelectedRow();

        // 1. Ninguém selecionado?—manda a real pro usuário.
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um endereço para excluir.");
            return;
        }

        // 2. Confirmação (não é obrigatório, mas é padrão corporativo)
        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir este endereço?", 
            "Confirmação", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        // 3. Captura o ID da linha selecionada (considerando que coluna 0 é o ID)
        int idEndereco = (int) tblEnderecos.getValueAt(row, 0);

        try {
            // 4. Chamar o controller para excluir
            EnderecoDAO dao = new EnderecoDAO();
            dao.excluir(idEndereco);

            // 5. Atualizar tabela
            atualizarTabela();

            JOptionPane.showMessageDialog(this, "Endereço excluído com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharEnderecoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharEnderecoActionPerformed

    private void btnMinimizarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarEnderecoActionPerformed
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEndereco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.RoundedButton btnEditar;
    private Componentes.RoundedButton btnExcluir;
    private Componentes.IconButton btnFecharEndereco;
    private Componentes.IconButton btnMinimizarEndereco;
    private Componentes.RoundedButton btnSalvar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnderecos;
    private Componentes.TextField txtBairro;
    private Componentes.TextField txtCep;
    private Componentes.TextField txtCidade;
    private Componentes.TextField txtDescricao;
    private Componentes.TextField txtLogradouro;
    private Componentes.TextField txtNumero;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
    enderecoSelecionado = null;
    txtDescricao.setText("");
    txtLogradouro.setText("");
    txtNumero.setText("");
    txtBairro.setText("");
    txtCidade.setText("");
    txtCep.setText("");
    cbxEstado.setSelectedIndex(0);
    btnSalvar.setText("Salvar");
    }

   private void atualizarTabela() {
        try {
            List<Endereco> lista = dao.listarPorUsuario(idUsuario);

            // AQUI ESTÁ O SEGREDO: Criamos o modelo sobrescrevendo o isCellEditable
            // Isso garante que NENHUMA célula seja editável, nunca.
            DefaultTableModel model = new DefaultTableModel(
                new String[]{
                    "ID", "Descrição", "Logradouro", "Número",
                    "Bairro", "Cidade", "Estado", "CEP"
                }, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // RETORNA FALSE SEMPRE = BLOQUEIA EDIÇÃO
                }
            };

            for (Endereco e : lista) {
                model.addRow(new Object[]{
                    e.getId(),
                    e.getDescricao(),
                    e.getLogradouro(),
                    e.getNumero(),
                    e.getBairro(),
                    e.getCidade(),
                    e.getEstado(),
                    e.getCep()
                });
            }

            tblEnderecos.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
        }
    }
    
}
